services:
  mavros:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.mavros
    ipc: host
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DISTRO=humble
      - ROS_DOMAIN_ID=1
      - GCS_URL=udp://@192.168.1.13
      - FCU_URL=/dev/ttyACM0
    security_opt:
      - seccomp:unconfined
    privileged: true
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0
    #   - /dev/ttyACM1:/dev/ttyACM1
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 81:* rmw' # Realsense
      - 'c 237:* rmw' # Realsense
      - 'c 226:* rmw' # /dev/dri/renderD128 for h264 encoding
    # depends_on:
    #   - ros
    #   - cacheproxy