services:
  mavros:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.mavros
    ipc: host
    network_mode: host
    environment:
      - ROS_DISTRO=humble
      - ROS_DOMAIN_ID=1
      - GCS_URL=udp://@192.168.1.13
      - FCU_URL=/dev/ttyACM0
    security_opt:
      - seccomp:unconfined
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0
    #   - /dev/ttyACM1:/dev/ttyACM1
    volumes:
      - /dev:/dev
    #   - ${HOME}/.hsr-omniverse/logs:/root/.nvidia-omniverse/logs:rw
    # depends_on:
    #   - ros
    #   - cacheproxy